version: "3.9"
services:
  joplin:
    build: .
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    command: ["sleep", "infinity"]
    volumes:
      - joplin:/root/.config/joplin
volumes:
  joplin:
