version: "3.9"
services:
  joplin:
    build: .
    restart: on-failure
    command: ["sleep", "infinity"]
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - joplin:/root/.config/joplin
volumes:
  joplin:
